### ISSUE TITLE
Deepankar's Todolist

### ISSUE THREAD

**Issue by Deep-Codes** [100mslive/100ms-docs#151]
# DEEP's TODO

- [x] fix order of content of android #148
- [x] fix Android Release notes #148
- [x] Mdx Components not working in Common Parts  #147
- [x] Fix Quickstart Apps Link in Basic Concepts in all Section #147
- [x] show message for people using old docs links `/v1` & `/v2` #149
- [x] add Android API reference up  #152 
- [x] better table UI #153
- [x] Tech Selector doesn't inherit the state from the `/api-reference` #153
- [x] Lowercase Tech Names in Selector #153
- [x] ~~skip to section not working for token generation page (fix: add remark-slug plugin)~~
- [x] Header new UI #153
- [x] Search Modal being cramped #153
- [ ] Javascript Release Notes not working (links to old docs)
- [ ] [Ask Praveen About this](https://100ms-live.slack.com/archives/C01FEBA0CGP/p1628692495153400)
- [ ] Report Transclusion Error to Hashicorp [POST MERGE]
